### ISSUE TITLE
Explore audio environment vibes

### ISSUE THREAD

**Issue by rafiftaris** [InShine-Studios/Horror-3D#100]

**Comment by RaiRiz** [comment]
The main points of the three scientific articles are listed in this document:
https://docs.google.com/document/d/1HEkNmpdkbXMycWSHisFN_0VqQZ_CjGLwh2FxZysN4Qk/edit?usp=sharing

**Comment by rafiftaris** [comment]
insightful papers! we can manage our audio development prioritization based on the paper

**Comment by raihansyahdean** [comment]
Well done! Hopefully we can implement your foundings in this project.
