### ISSUE TITLE
Adjust MUS_HouseAbigail_1_Loop to intended usage

### ISSUE THREAD

**Issue by raihansyahdean** [InShine-Studios/Horror-3D#128]

**Comment by RaiRiz** [comment]
Aset audio "MUS_HouseAbigail_1_Loop" akan dialihfungsikan menjadi audio lobby sehingga akan bernama "MUS_Lobby_1_Loop"

**Comment by RaiRiz** [comment]
The audio asset "MUS_Lobby_1_Loop" needs to be trimmed before it can be used as music in the lobby/waiting room
