### ISSUE TITLE
Hide Mechanic

### ISSUE THREAD

**Issue by uciii** [InShine-Studios/Horror-3D#149]
- Player prefab masuk ke lemari
- Screen overlay jadi obsucred (liat milanote)
- matiin movement (tanya uci), mainin input system

**Comment by raihansyahdean** [comment]
Flow:
1. auto pindah ke dalem lemarinya dan gabisa gerak
2. Screen overlay muncul (cek milanote)
3. Kalo di pencet key lagi keluar
