### ISSUE TITLE
Implement script to make an audio faster or slower

### ISSUE THREAD

**Issue by uciii** [InShine-Studios/Horror-3D#152]
make sure test case has:
- delay so tester can hear the audio when running test case
- assert the speed of the audio
- testing is done with heart beat audio

**Comment by RaiRiz** [comment]
Some possible workarounds:

1. using middleware (Unity can be directly integrated with FMOD)
2. set up several SFX which are exactly the same as the existing SFX heartbeat but with different speeds. Later which SFX to use depends on the distance between the player and the ghost
3. try suggestions from these forums: https://answers.unity.com/questions/316007/slow-down-sound.html https://answers.unity.com/questions/25139/how-i-can-change-the-speed-of-a-song-or-sound.html https://stackoverflow.com/questions/51572932/changing-tempo-of-music-track-in-unity3d

**Comment by RaiRiz** [comment]
because the 4th option is chosen, no script will be implemented
