### ISSUE TITLE
Implement script that plays player dies audio from GM

### ISSUE THREAD

**Issue by raihansyahdean** [InShine-Studios/Horror-3D#166]
- Script is called PlayerStates attached in all Player prefabs.
- Use observer pattern to notify GM
- Add AudioManager to GM and a function that will play that Audio

**Comment by RaiRiz** [comment]
- Since only Iris prefab available for now, attach the PlayerStates.cs to Iris
- The player with dies status acts as Publisher while GameManager (GM) acts as Subscriber
- Function to play audio could just be copas-ed from another script
