### ISSUE TITLE
RV layout +  item placement 

### ISSUE THREAD

**Issue by rafiftaris** [InShine-Studios/Horror-3D#181]

**Comment by VadimBhirawa** [comment]
Milanote: https://app.milanote.com/1N0nmA1lx8iN2X/world-building?p=bOJzjVxeHMY
Figma: https://www.figma.com/file/DsszNQszZ2Li3Net1W2gcr/RV-Layout?node-id=0%3A1

**Comment by uciii** [comment]
Guud layout 👍

**Comment by ahmadhaydar** [comment]
Seal of Approval

**Comment by JahnsMichael** [comment]
approved

**Comment by naufalhilmi12345** [comment]
Cool! LGTM
