### ISSUE TITLE
[Refactor] Remove player states condition in GM

### ISSUE THREAD

**Issue by uciii** [InShine-Studios/Horror-3D#212]
Breakdown InvokePlayerState function to several functions

**Comment by raihansyahdean** [comment]
Currently flow from GM to HM and HM to GM uses multiple events and functions. Try to make it generic and only use one function. GM to HM and HM to GM make only one function

**Comment by raihansyahdean** [comment]
In ExorcismBar class, please Rename ShowBar() to SetExorcismBar() as setter
