### ISSUE TITLE
[Refactor] Closest interactable called on every update (+ titipan)

### ISSUE THREAD

**Issue by uciii** [InShine-Studios/Horror-3D#214]
Fix with player -> NearbyItems
NearbyItems class is similar to inventory.
NearbyItems nyimpen item mana aja yang lagi di zona player.
Kalo player udah keluar dari zona item, keluarin item dari list NearbyItems

Still call on every update but no longer cast on every frame

Rename _movementSpeed in PlayerBase

Refactor, put _detectorZone in abstract. Fix Start() to Awake()

Raname funcs in ObjectDetector

**Comment by raihansyahdean** [comment]
In Item class, put IsDiscardedWhenUsed() to set get
