### ISSUE TITLE
[Rework] Hiding and closet interaction

### ISSUE THREAD

**Issue by uciii** [InShine-Studios/Horror-3D#312]
- Liat milanote untuk implement terbaru [https://app.milanote.com/1NzRxK116UBW1s/hiding?p=bOJzjVxeHMY](https://app.milanote.com/1NzRxK116UBW1s/hiding?p=bOJzjVxeHMY)

**Comment by InShineStudios** [comment]
- Become First Person
- Animasi Pintu (Open and Close)
- Jalan player masuk ke closet
- Bagi jadi 2 bagian closetnya (kiri kanan)

**Comment by InShineStudios** [comment]
Become first person no longer valid

**Comment by rafiftaris** [comment]
Closet interactablenya jadi 1 aja
