### ISSUE TITLE
Model and texture for Astral World Visual Ambience

### ISSUE THREAD

**Issue by uciii** [InShine-Studios/Horror-3D#323]
- Texture sheet for animated eye
- Texture sheet for animated ghost hand

**Comment by ahmadhaydar** [comment]
![unknown-48](https://user-images.githubusercontent.com/78914402/166891831-b6e9389e-4557-4402-968a-3c76e9df9b7d.png)
![Animation1-1](https://user-images.githubusercontent.com/78914402/166891838-352c8769-23b0-4607-bef6-7820a5fda61b.gif)
* hand includes outline (the gif is example usage of hand)
* eyes already been put in short movie
* check files @ asset thread archive
