### ISSUE TITLE
[3D Model] Ghost: Rakshasa

### ISSUE THREAD

**Issue by InShineStudios** [InShine-Studios/Horror-3D#336]

**Comment by ahmadhaydar** [comment]
![idle](https://user-images.githubusercontent.com/78914402/178303920-5955357d-c031-4428-b785-503dd5ea33b2.gif)
![walk](https://user-images.githubusercontent.com/78914402/178303972-0473c170-f9bd-461d-a2f2-d7c044ba5042.gif)

**Comment by JahnsMichael** [comment]
bungkuss
