### ISSUE TITLE
Inventory: Implement shoulder flashlight for characters

### ISSUE THREAD

**Issue by InShineStudios** [InShine-Studios/Horror-3D#341]
- Key bind for automatic use (discuss with designers)
- Make it not an item in inventory

**Comment by rafiftaris** [comment]
## Guideline

### Flashlight prefab
Note: **Modif di prefabnya langsung, jangan di scene**
- Rename class DummyFlashlightItem jadi Flashlight, inherit MonoBehaviour jangan Item (sesuain juga comment docsnya)
- Rename DummyFlashlight.prefab jadi Flashlight.prefab
- Awake() yg awalnya protected override dibikin jadi private aja
- Use(): ilangin override

### Iris prefab
Note: **Modif di prefabnya langsung, jangan di scene**
- Ilangin gameobject flashlight
- Pasang prefab flashlight di tempat gameobject flashlight yg lama

### Player Input
Note: **Modif di prefabnya langsung, jangan di scene**
- Di prefab Iris ada component Player Input, disitu ada Actions. Double click PlayerInputActions buat ngebuka control schemes
- Di action map default, tambahin action baru (pencet tombol plus) dan namain "ToggleFlashlight"
- Tambahin binding baru di action "ToggleFlashlight". Isi path sesuai tombol buat toggle flashlight, checklist "Use in control scheme Keyboard&Mouse"
- Jangan lupa buat klik Save Asset
- Tutup pop-up window dan cek inspector dari iris lagi, bagian Player Input
- Buka dropdown Events -> Default, cari "ToggleFlashlight"
- Drag Component Input Manager (di paling bawah inspector) ke slot kosong yg ada tulisan (Object)
- Buka dropdown function, ke input manager dan pilih HandleInputDefault

### Scripts
- **InputManager.cs**: Di fungsi HandleInputDefault, tambahin case baru "ToggleFlashlight". Isinya samain kyk yg lain tapi rename fungsinya jadi ToggleFlashlight
- **PlayerState.cs**: Di region Default Input Handler, tambahin fungsi ToggleFlashlight (ikutin fungsi yg lain)
- **PlayerDefaultState.cs**: Bikin region baru "Accessory Input Handler", override fungsi ToggleFlashlight
