### ISSUE TITLE
[Adjust] Design inventory and items

### ISSUE THREAD

**Issue by InShineStudios** [InShine-Studios/Horror-3D#361]
- What are items in the game? Usages, types, etc.?
- Inventory for players, how does it work?
- Inventory HUD? Needed or not?

**Comment by rafiftaris** [comment]
The design looks good and feasible to be implemented. But I have some questions:
- Is there any button to access mindmap and inventory directly? Or these menus have to be accessed from the "access menu"?


In addition, these are some concern in the programming parts:
- Idk (yet) how to make the mindmap graph placement not stiff. Is the placement dynamically programmed or manually placed? (I hope there's a package to implement this easily)


That is all from me. Thank you.

**Comment by JahnsMichael** [comment]
LGTM!!! my only concern has been discussed and answered in the discord chat. Thank you~
