### ISSUE TITLE
[feature] Chapter Clues

### ISSUE THREAD

**Issue by InShineStudios** [InShine-Studios/Horror-3D#382]
1. Breakdown programming structure and design of the feature
2. Propose solutions and discuss with Dean
3. Implement and test

Liat milanote dan figma untuk detail (https://www.figma.com/file/2t6pNFH4ygc399uDNo4n2k/Lo-Fi-Inventory?node-id=0%3A1)
Ask designers if needed

**Comment by rafiftaris** [comment]
inspect object tutorial: https://youtu.be/cu39TdzirCE
