### ISSUE TITLE
Chapter clues camera and navigation

### ISSUE THREAD

**Issue by InShineStudios** [InShine-Studios/Horror-3D#402]
## Task Scope
- Move (**with animation/tween**, not instantly) camera when a chapter or core node is selected
- Add UI for navigation (check [figma](https://www.figma.com/file/2t6pNFH4ygc399uDNo4n2k/Lo-Fi-Inventory?node-id=0%3A1), upper right and upper left corner)
- Chapter navigation (upper left corner) functionality cant be tested until there's another dummy chapter
- Core navigation (upper right corner) functionality **must be tested** and works well

## Note
- Add new camera just for chapter clues. This camera only renders chapter clues menu
- Disable all other cameras when chapter menus is open. Enable all and disable the new camera otherwise

**Comment by rafiftaris** [comment]
BUG: ScriptableObject doesn't store nodes' transform. Expected to be fixed here
