### ISSUE TITLE
Init Sound Design Document

### ISSUE THREAD

**Issue by rafiftaris** [InShine-Studios/Horror-3D#43]

**Comment by RaiRiz** [comment]
Mohon reviewnya kakak2 @rafiftaris @uciii , cc: @raihansyahdean 
- Sound Design Document (Template): https://docs.google.com/document/d/1dn7KF7lF2_0GCGYUYJnsgcFtQpniRHkt2yCO4YB7j9U/edit?usp=sharing
- SDD untuk proyek game kali ini: https://docs.google.com/document/d/1qtph1TXIIrCCePx5uRqV7lrnYFL0YuJj9CjVV7SUXSc/edit?usp=sharing
- Quote/Sound List (Template): https://docs.google.com/spreadsheets/d/12A6Q8jH2KAkY_peGqkhRuICQrCpAm4onrmjzJ5gXggg/edit?usp=sharing
- Quote/Sound List untuk proyek game kali ini: (belom ada sih wkwk, nanti akan diisi ketika sudah ada prototype yang cukup bisa dipakai)
