### ISSUE TITLE
Fill QS List with existing Audio in Project

### ISSUE THREAD

**Issue by uciii** [InShine-Studios/Horror-3D#68]

**Comment by RaiRiz** [comment]
Mohon reviewnya @naufalhilmi12345 @ahmadhaydar , cc: @raihansyahdean 
Link QS List: https://docs.google.com/spreadsheets/d/1gsHRRFwN4QyYJzZvs9QmzklRW7wCB5ivEE4ZGU4QDK4/edit?usp=sharing

**Comment by naufalhilmi12345** [comment]
Cool! LGTM

**Comment by GustiNgurahYama** [comment]
so far so gud

**Comment by ahmadhaydar** [comment]
yeet
