### ISSUE TITLE
Concepting Logo Studio

### ISSUE THREAD

**Issue by raihansyahdean** [InShine-Studios/Horror-3D#78]

**Comment by ahmadhaydar** [comment]
![Logo1](https://user-images.githubusercontent.com/78914402/150472557-0c3dd60e-5e2a-465d-b10b-e0b06e16ead0.png)
![Logo2](https://user-images.githubusercontent.com/78914402/150472564-4bfa9138-0576-439a-8fb1-d130f896d7b7.png)
![Logo3](https://user-images.githubusercontent.com/78914402/150472563-01669d04-4cd1-4d87-ad2c-501819308c98.png)

**Comment by raihansyahdean** [comment]
Very very nice!

**Comment by VadimBhirawa** [comment]
Nice!

**Comment by RaiRiz** [comment]
jujur paling suka yg teratas tapi semuanya bagus 👍

**Comment by JahnsMichael** [comment]
dah mantep, dah disesuain buat beberapa format juga, approved!!

**Comment by uciii** [comment]
mantab gan

**Comment by rafiftaris** [comment]
kereenn
