### ISSUE TITLE
[Concept Art] Indoor "Kill Phase" (Astral World)

### ISSUE THREAD

**Issue by raihansyahdean** [InShine-Studios/Horror-3D#84]

**Comment by ahmadhaydar** [comment]
![1643193819555](https://user-images.githubusercontent.com/78914402/151296452-4624ebef-4686-4306-9fa5-ba1fc0172f80.png)

**Comment by RaiRiz** [comment]
😳😳😳. Approved!

**Comment by GustiNgurahYama** [comment]
*muehehehe

**Comment by JahnsMichael** [comment]
mantep bener dah~
