### ISSUE TITLE
[Concept Art] Outdoor Investigation Team + Vehicle

### ISSUE THREAD

**Issue by rafiftaris** [InShine-Studios/Horror-3D#88]

**Comment by ahmadhaydar** [comment]
![1643719491719](https://user-images.githubusercontent.com/78914402/151971170-9cca209f-d4d1-401c-a495-1e3f7d996b29.png)

**Comment by RaiRiz** [comment]
GG! Approved.

**Comment by uciii** [comment]
Herc Oppa
